# -*- coding: utf-8 -*-
"""Assignment_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z9whwzzdFYeBz8AcNPTIWe1owhxX643t
"""

# Task 1: Read a File and Handle Errors

try:
    with open("sample.txt", "r") as file:
        for line in file:
            print(line, end='')  # end='' to avoid double newlines
except FileNotFoundError:
    print("Error: 'sample.txt' does not exist.")

# Task 2: Write and Append Data to a File

user_input = input("Enter some data: ")


with open("output.txt", "w") as file:
    file.write(user_input + "\n")


additional_data = "This is additional data."
with open("output.txt", "a") as file:
    file.write(additional_data + "\n")


with open("output.txt", "r") as file:
    content = file.read()
    print("Final file content:")
    print(content)

